### ISSUE TITLE
Project Home Page

### ISSUE THREAD

**Issue by seanpoulter** [fabianhu/LiPoHoTT#1]
Hi Fabian,

I've been looking around for a 6S voltage sensor and found your build. The home page at https://www.huslik-elektronik.de/cms/embedded-hardware/31-lipohott is down. Would you be able to share those docs with me? I'm happy to open a PR to the repo in Markdown format.

Thanks and all the best from Ottawa, Canada. 🇨🇦

PS: That Tesla API is a really neat project!

**Comment by fabianhu** [comment]
Hi Sean,
I just looked into my backups and put all files into the doc folder.
I would recommend, to import the Eagle files into Kicad.
The firmware could be built with the legacy AVR Studio.
I'm sure, there is a ton, that should be done differently now.
